### ISSUE TITLE
Does not work with Glyphs 1.4.5

### ISSUE THREAD

**Issue by synthview** [DeutschMark/Glyphsapp-Plugins#1]
Hi!
your plugin seems to work on G2, but nothing appears on G1.4.5

**Comment by DeutschMark** [comment]
Yes, it is just developed for G2. I’ll have a look at if I can fix that. Thanks.

**Comment by DeutschMark** [comment]
I see the problem with G1, it uses python 2.6. instead of 2.7 (G2). I need way to get the index of a list item without using the .index() method for G1. If anyone knows how to do that?

**Comment by Mark2Mark** [comment]
Workaround implemented. Problem fixed. Should work now in Glyphs 1 as well

**Comment by synthview** [comment]
works! :+1:  Thank you for providing this  future retro-compatibility

**Comment by Mark2Mark** [comment]
Thanks for pointing this issue!
