### ISSUE TITLE
Where did Show Next Master go?

### ISSUE THREAD

**Issue by weiweihuanghuang** [DeutschMark/Glyphsapp-Plugins#4]
I know this repo hasn't been udpated in a while but I can't find this nifty plug-in anymore? Was it deleted?

**Comment by Mark2Mark** [comment]
Ha, the most silly plugin I ever made. It was for a very specific project, but I guess in similar specific projects it could be useful.

I am not sure if it even supports Glyphs 3 yet. Last changes are 5 and 7 years old. I just pushed a gitignore update now.

Here it is:
https://github.com/Mark2Mark/Show-Next-Master

(Yes, I never find time to update this and the scripts repo 😔)
